spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: user-service-hateoas-route
          uri: lb://user-service
          predicates:
            - Path=/api/v2/users/**
        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker
                fallbackUri: forward:/fallback/notifications

resilience4j:
  circuitbreaker:
    instances:
      notificationServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

eureka:
  instance:
    prefer-ip-address: true
